### ISSUE TITLE
Do not display processed point clouds

### ISSUE THREAD

**Issue by ZhangAlso** [baberjunaid/LiDAR_Tracking_3D#1]
Hello, I ran your program and only the original point cloud data was displayed in rviz. When I switched the topic to outputs and roi, the processed point cloud was not displayed. Do you know what the problem is? I use the ouster-128

**Comment by baberjunaid** [comment]
Could you please share the screenshot of the terminal and also rviz?

sorry for late response.

**Comment by ZhangAlso** [comment]
> Could you please share the screenshot of the terminal and also rviz?
> 
> sorry for late response.

Thanks for your reply, I have solved the problem. I found that there was a problem when subscribing to the input point cloud. So I changed the subscription topic from input directly to /ouster/points in the main function. Thank you again for your reply.
